@startuml
participant J
participant Shaggy 
note left of J #Aqua
will be shown 
to the left of J
end note

note right of J: will be shown to the right of J

note over J: will be shown above J
note over J, Shaggy #FF000F: will be shown \n above them both.

note over Shaggy, J
This is
another example of
long note.
end note 
@enduml