@startuml
skinparam SequenceMessageAlign right
Bob -> Alice : Request
Alice -> Bob : Response
@enduml

@startuml
skinparam ResponseMessageBelowArrow true
Bob -> Alice : give me 5 euros
Alice -> Bob : no 
@enduml