@startuml

J -> Shaggy : message 1
J -> Shaggy : message 2

newpage 

J -> Shaggy : message 3
J -> Shaggy : message 4

newpage A title for the/nlast page 

J -> Shaggy : message 5
J -> Shagge : message 6
@enduml
